#!/usr/bin/env bash
set -e

if [ ! -f .venv/bin/python ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
    echo "Installing dependencies..."
    .venv/bin/python -m pip install -r requirements.txt
fi

.venv/bin/python -m src.cli.main "$@"
