name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Run Code Linter (Ruff)
        run: uv run ruff check .

      - name: Run Code Formatter (Ruff)
        run: uv run ruff format --check .

      - name: Check Translation Integrity (Babel)
        run: uv run pybabel compile -d locales --statistics

      - name: Run tests
        run: uv run pytest
